import { cleanThreadName, parseTimestamp } from './helpers';

// --- Facebook Messenger HTML Parser ---
export function parseHTML(html, filePath, myNames, fileRegistry) {
  const messages = [];
  const media = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  let rawName = 'Unknown Chat';
  const titleEl = doc.querySelector('title');
  if (titleEl) rawName = titleEl.textContent.trim();
  const folderHint = filePath ? filePath.split('/').slice(-2, -1)[0] || '' : '';

  // Extract "Generated by [Name]" — works on start_here.html, chat pages, and any FB export page
  let generatedBy = null;
  const asideEl = doc.querySelector('aside._aoaa, aside[role="contentinfo"]');
  if (asideEl) {
    const match = asideEl.textContent.match(/Generated by\s+(.+?)\s+on\s/i);
    if (match) generatedBy = match[1].trim();
  }
  // Fallback: search full HTML text for the pattern (catches start_here.html and variants)
  if (!generatedBy) {
    const fullMatch = html.match(/Generated by\s+([^<]+?)\s+on\s/i);
    if (fullMatch) generatedBy = fullMatch[1].trim();
  }

  // Collect unique sender names as participants
  const participantSet = new Set();

  // Try known obfuscated class first, then fall back to structural matching
  // Facebook regenerates obfuscated class names across export versions
  let sections = doc.querySelectorAll('section._a6-g');
  let useStructural = false;
  if (sections.length === 0) {
    // Structural fallback: any section/div that contains an h2 (sender) and a footer (date)
    const candidates = doc.querySelectorAll('section, div[role="main"] > div > div');
    const matched = [];
    candidates.forEach(el => {
      if (el.querySelector('h2') && el.querySelector('footer')) matched.push(el);
    });
    if (matched.length > 0) {
      sections = matched;
      useStructural = true;
    }
  }

  if (sections.length === 0) return { messages, media, participants: [], generatedBy };

  let dirPath = filePath ? filePath.split('/').slice(0, -1).join('/') + '/' : '';

  // First pass: collect all senders so we can resolve threadName using real participant names
  sections.forEach(sec => {
    const senderEl = sec.querySelector('h2');
    const sender = senderEl ? senderEl.textContent.trim() : 'Unknown';
    if (sender && sender !== 'Unknown') participantSet.add(sender);
  });

  // Resolve threadName now that we have real participant names from the file
  const threadName = cleanThreadName(rawName, Array.from(participantSet), myNames, folderHint);

  const source = 'HTML (' + (filePath ? filePath.split('/').slice(-2).join('/') : 'Unknown') + ')';

  sections.forEach(sec => {
    const senderEl = sec.querySelector('h2');
    // Skip Word effects sections — no h2, content starts with "Word:" metadata
    if (!senderEl && sec.textContent.trim().startsWith('Word:')) return;
    // Content: try known class first, then any div between h2 and footer
    let contentEl = sec.querySelector('._a6-p');
    if (!contentEl) {
      // Fallback: find the div that sits between the h2 and footer — it holds message content
      const divs = Array.from(sec.querySelectorAll(':scope > div, :scope > div > div'));
      for (const d of divs) {
        if (!d.querySelector('h2') && !d.querySelector('footer') && d.textContent.trim()) {
          contentEl = d;
          break;
        }
      }
    }
    const footerEl = sec.querySelector('footer');
    const sender = senderEl ? senderEl.textContent.trim() : 'Unknown';
    // Date is inside footer > div._a72d, not directly in footer
    let dateStr = '';
    if (footerEl) {
      const dateDiv = footerEl.querySelector('._a72d') || footerEl;
      dateStr = dateDiv.textContent.trim();
    }
    // Word effects sections have no footer — extract "Creation time:" from content
    if (!dateStr && !senderEl) {
      const creationMatch = sec.textContent.match(/Creation time:\s*(.+?)(?:\n|$)/i);
      if (creationMatch) dateStr = creationMatch[1].trim();
    }

    let contentText = contentEl
      ? contentEl.cloneNode(true).textContent.replace(/\s+/g, ' ').trim()
      : '';

    // Extract reactions
    const reactions = [];
    sec.querySelectorAll('li, ._a6-q, [class*="reaction"]').forEach(el => {
      const t = el.textContent.trim();
      if (t && t.length <= 5) reactions.push(t); // short = emoji reaction
    });

    let hasMedia = false;
    sec.querySelectorAll('img').forEach(img => {
      const src = img.getAttribute('src');
      if (src) {
        hasMedia = true;
        const mediaItem = resolveMedia(src, dirPath, threadName, sender, dateStr, 'image', fileRegistry);
        if (mediaItem) media.push(mediaItem);
      }
    });

    sec.querySelectorAll('a').forEach(a => {
      const href = a.getAttribute('href');
      const text = a.textContent.trim();
      if (href && (href.includes('files/') || text.includes('Download file'))) {
        hasMedia = true;
        const mediaItem = resolveMedia(href, dirPath, threadName, sender, dateStr, 'file', fileRegistry);
        if (mediaItem) media.push(mediaItem);
      }
    });

    // For media-only messages (no text), use a placeholder so the message isn't lost
    if (!contentText && hasMedia) contentText = '[Media]';
    // For audio messages — look for audio elements
    if (!contentText && sec.querySelector('audio')) contentText = '[Audio]';

    if (contentText) {
      messages.push({
        threadName, sender, content: contentText, dateStr,
        timestamp: parseTimestamp(dateStr), reactions,
        _platform: 'Messenger',
        _source: source
      });
    }
  });

  return { messages, media, participants: Array.from(participantSet), generatedBy };
}

// Decode Facebook's broken UTF-8 encoding (Latin-1 bytes stored as Unicode code points)
function decodeFBString(str) {
  if (!str) return str;
  try {
    // Facebook encodes UTF-8 bytes as Latin-1 characters — decode them back
    return decodeURIComponent(escape(str));
  } catch (e) {
    return str; // Return original if decoding fails
  }
}

// --- Facebook Messenger JSON Parser ---
export function parseJSON(text, filePath, myNames, fileRegistry) {
  const messages = [];
  const media = [];
  let data;
  try { data = JSON.parse(text); } catch (e) { return { messages, media }; }
  if (!data.messages || !Array.isArray(data.messages)) return { messages, media, participants: [] };

  let rawTitle = decodeFBString(data.title || data.threadName || '');
  let parsedParticipants = [];
  if (Array.isArray(data.participants)) {
    parsedParticipants = data.participants
      .map(p => (typeof p === 'object' && p.name ? decodeFBString(p.name) : (typeof p === 'string' ? decodeFBString(p) : '')))
      .filter(Boolean);
  }
  let threadName = cleanThreadName(rawTitle, parsedParticipants, myNames);

  const pathParts = filePath.split('/');
  const fileName = pathParts.pop();
  const folderName = pathParts.pop() || '';
  const dirPath = [...pathParts, folderName].filter(Boolean).join('/') + '/';
  const displayPath = folderName ? `${folderName}/${fileName}` : fileName;
  const jsonFolderName = fileName.replace('.json', '');

  data.messages.forEach(msg => {
    if (msg.isUnsent || msg.is_unsent) return;

    // Skip system/meta message types that aren't real conversations
    const msgType = (msg.type || '').toLowerCase();
    if (msgType === 'subscribe' || msgType === 'unsubscribe') return;

    const sender = decodeFBString(msg.senderName || msg.sender_name) || 'Unknown';
    const content = decodeFBString(msg.text || msg.content) || '';

    // Skip "word effects" and other Messenger system metadata
    if (!content && !msg.share && !msg.sticker && !msg.photos && !msg.videos &&
        !msg.audio_files && !msg.files && !msg.gifs && !msg.media) return;
    let dateStr = '';
    let timestamp = msg.timestamp_ms || msg.timestamp || 0;
    if (timestamp) dateStr = new Date(timestamp).toLocaleString();
    const reactions = msg.reactions ? msg.reactions.map(r => r.reaction || r.emoji || r) : [];

    // Handle media from both standard and E2EE export formats
    const mediaArrays = [msg.media, msg.photos, msg.videos, msg.audio_files, msg.files, msg.gifs].filter(Boolean);
    const hasMedia = mediaArrays.some(arr => arr && arr.length > 0);
    mediaArrays.forEach(arr => {
      if (!arr) return;
      arr.forEach(m => {
        const uri = m.uri || m.creation_timestamp;
        if (uri && typeof uri === 'string') {
          const mediaItem = resolveMedia(
            dirPath + `${jsonFolderName}/${uri.replace(/^\.\//, '')}`,
            dirPath, threadName, sender, dateStr, 'image', fileRegistry
          );
          if (mediaItem) media.push(mediaItem);
        }
      });
    });

    // Build display content — include share links and sticker references
    let displayContent = content;
    if (!displayContent && msg.share && msg.share.link) displayContent = `[Shared: ${msg.share.link}]`;
    if (!displayContent && msg.sticker && msg.sticker.uri) displayContent = '[Sticker]';
    if (!displayContent && hasMedia) displayContent = '[Media]';

    if (displayContent || hasMedia) {
      messages.push({
        threadName, sender, content: displayContent || '[Media]', dateStr,
        timestamp, reactions,
        _platform: 'Messenger',
        _source: 'JSON (' + displayPath + ')'
      });
    }
  });

  return { messages, media, participants: parsedParticipants };
}

// --- WhatsApp TXT Parser ---
export function parseWhatsAppTXT(text, filename, myNames, dateFormat = 'auto') {
  const messages = [];
  let rawName = filename.replace('.txt', '').replace(/^WhatsApp Chat with /i, '').trim();
  let threadName = cleanThreadName(rawName, [], myNames);

  const lines = text.split(/\r?\n/);
  const messageRegex = /^\[?(\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}[, ]+\d{1,2}:\d{2}(?::\d{2})?(?:\s*[AaPp][Mm])?)\]?\s*[\-]?\s*([^:]+):\s*(.*)$/;

  // Use user-specified date format if not 'auto', otherwise auto-detect
  let currentDateOrder = null;
  if (dateFormat === 'DMY' || dateFormat === 'MDY') {
    currentDateOrder = dateFormat;
  } else {
    for (let i = 0; i < lines.length; i++) {
      const match = lines[i].match(messageRegex);
      if (match) {
        const dMatch = match[1].match(/(\d{1,2})[\/\-\.](\d{1,2})[\/\-\.](\d{2,4})/);
        if (dMatch) {
          const p1 = parseInt(dMatch[1], 10);
          const p2 = parseInt(dMatch[2], 10);
          if (p1 > 12 && p2 <= 12) {
            currentDateOrder = 'DMY'; break;
          } else if (p1 <= 12 && p2 > 12) {
            currentDateOrder = 'MDY'; break;
          }
        }
      }
    }
  }

  let currentMsg = null;

  lines.forEach(line => {
    const match = line.match(messageRegex);
    if (match) {
      if (currentMsg) messages.push(currentMsg);
      const sender = match[2].trim();
      const dateStr = match[1].trim();
      
      const dMatch = dateStr.match(/(\d{1,2})[\/\-\.](\d{1,2})[\/\-\.](\d{2,4})/);
      if (dMatch) {
        const p1 = parseInt(dMatch[1], 10);
        const p2 = parseInt(dMatch[2], 10);
        if (p1 > 12 && p2 <= 12) currentDateOrder = 'DMY';
        else if (p1 <= 12 && p2 > 12) currentDateOrder = 'MDY';
      }

      currentMsg = {
        threadName, sender, dateStr,
        timestamp: parseTimestamp(dateStr, currentDateOrder),
        content: match[3].trim(),
        reactions: [],
        _platform: 'WhatsApp',
        _source: 'TXT (' + filename + ')'
      };
    } else {
      if (currentMsg && line.trim() !== '') currentMsg.content += '\n' + line;
    }
  });
  if (currentMsg) messages.push(currentMsg);

  return { messages, media: [] };
}

// --- SMS NDJSON Parser ---
export function parseNDJSON(text, filename, myNames) {
  const messages = [];
  const lines = text.split(/\r?\n/);

  lines.forEach(line => {
    if (!line.trim()) return;
    try {
      const data = JSON.parse(line);
      let rawThreadName = data.__display_name || data.address || 'Unknown SMS';
      let threadName = cleanThreadName(rawThreadName, [], myNames);

      let sender = 'Unknown';
      // Android Telephony API: only type 2 = sent. Types 1,3,4,5,6 are not sent.
      const smsType = String(data.type);
      const isSent = smsType === '2';
      if (isSent) {
        sender = myNames.length > 0 ? myNames[0] : 'Me';
      } else {
        sender = data.__display_name || data.address || 'Unknown';
      }

      let content = data.body || '';
      let timestamp = data.date ? parseInt(data.date) : 0;
      let dateStr = timestamp ? new Date(timestamp).toLocaleString() : '';

      if (content) {
        messages.push({
          threadName, sender, content, dateStr,
          timestamp, reactions: [],
          _platform: 'SMS',
          _source: 'NDJSON (' + filename + ')'
        });
      }
    } catch (e) { /* skip invalid lines */ }
  });

  return { messages, media: [] };
}

// --- SMS JSON Array Parser ---
export function parseSMSJSON(text, filename, myNames) {
  const messages = [];
  let data;
  try { data = JSON.parse(text); } catch (e) { return { messages, media: [] }; }
  if (!Array.isArray(data)) return { messages, media: [] };

  data.forEach(sms => {
    if (!sms.body || !sms.address) return;

    const rawAddress = sms.address || 'Unknown SMS';
    const threadName = cleanThreadName(rawAddress, [], myNames);

    // Android Telephony API: only type 2 = sent. Types 1,3,4,5,6 are not sent.
    let sender;
    const smsType = String(sms.type);
    const isSent = smsType === '2';
    if (isSent) {
      sender = myNames.length > 0 ? myNames[0] : 'Me';
    } else {
      sender = rawAddress;
    }

    const content = sms.body || '';
    const timestamp = sms.date ? parseInt(sms.date) : 0;
    const dateStr = timestamp ? new Date(timestamp).toLocaleString() : '';

    if (content) {
      messages.push({
        threadName, sender, content, dateStr,
        timestamp, reactions: [],
        _platform: 'SMS',
        _source: 'SMS JSON (' + filename + ')'
      });
    }
  });

  return { messages, media: [] };
}

// --- Media Resolution Helper ---
function resolveMedia(path, baseDir, threadName, sender, dateStr, type, fileRegistry) {
  let fileObj = fileRegistry[path];
  if (!fileObj) {
    const filename = path.split('/').pop();
    const matchKey = Object.keys(fileRegistry).find(
      key => key.endsWith(filename) && key.startsWith(baseDir)
    );
    if (matchKey) fileObj = fileRegistry[matchKey];
  }
  if (fileObj) {
    return {
      type, url: URL.createObjectURL(fileObj),
      filename: fileObj.name, threadName, sender, dateStr
    };
  }
  return null;
}
